# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=None, upload_to='MEDIA_ROOT'),
        ),
    ]
