# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='./media/'),
        ),
    ]
