# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=255)),
                ('githubProfile', models.CharField(max_length=255)),
                ('linkedinProfile', models.CharField(max_length=255)),
            ],
        ),
    ]
