# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0002_contactform_pgppublickey'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='ContactInfo',
        ),
    ]
